#c.f. https://docs.python.org/3.6/library/logging.html#logrecord-attributesls


version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: '%(asctime)s %(name)s %(filename)s %(funcName)s %(levelname)s %(message)s'
    datefmt: '%d/%m/%Y %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stderr
    formatter: simple

  file:
    (): DarknessPipeline.Utils.pipelinelog.MakeFileHandler
    filename: default.log
    mode: a
    level: DEBUG
    formatter: simple

root:
  level: DEBUG
  handlers: [console]
